### ISSUE TITLE
theta3 wrongly gives 1 in some cases

### ISSUE THREAD

**Issue by ahstat** [RobinHankin/elliptic#7]
Hello,
thanks for building this package

theta3 function wrongly returns 1 in some specific cases. For instance:

`theta3(z = pi/4, q = exp(-pi/4), maxiter = 10000)` gives 1 whereas it should give 0.9135722, such as observed for `theta3(z = pi/4+1e-15, q = exp(-pi/4), maxiter = 10000)`.

The issue is the number of iterations that stops after the first step.
This is not sufficient to allow a minimum number of steps, for instance:

`theta3(z = pi/4, q = exp(-pi/16), maxiter = 10000)` gives 1 whereas it should give 0.1745516, such as observed for `theta3(z = pi/4+1e-15, q = exp(-pi/16), maxiter = 10000)`.

Here comparing with the 2-step previous value would solve the issue, but it may not solve it in all cases.

**Comment by RobinHankin** [comment]
ahstat, thanks for this.   Clearly a bug.  I have not worked on the package for many years (and let's just say I've learned a lot about R and indeed elliptic functions since).


``` r
suppressMessages(library('elliptic'))

theta3(z = pi/4, q = exp(-pi/4), maxiter = 10000)
#> [1] 1
theta3(z = pi/4+1e-15, q = exp(-pi/4), maxiter = 10000)
#> [1] 0.9135722


theta3(z = pi/4, q = exp(-pi/16), maxiter = 10000)
#> [1] 1
theta3(z = pi/4+1e-15, q = exp(-pi/16), maxiter = 10000)
#> [1] 0.1745516
```

<sup>Created on 2023-11-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by RobinHankin** [comment]
FWIW, mathematica agrees with the offset values above:

```
In[5]:= EllipticTheta[3,Pi/4,Exp[-Pi/4]+0.0]                                                                                                                                                                                           
Out[5]= 0.913579

In[6]:= EllipticTheta[3,Pi/4,Exp[-Pi/16]+0.0]                                                                                                                                                                                          
Out[6]= 0.172856
```

**Comment by RobinHankin** [comment]
see also issue #8
